package systemTests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.openqa.selenium.NotFoundException;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;



@RunWith(Parameterized.class)
public class LoginTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	private String username;
	private String pwd;

	public LoginTest(String username, String pwd) {
		super();
		this.username = username;
		this.pwd = pwd;
	}


	@Before
	public void setUp() {
		// Setting up path to Google Chrome driver (chdriver)
		//System.setProperty("webdriver.chrome.driver", "/Users/kianmaroofi/git/repository/PMS/chdriver");
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\kianm\\repos\\CEN4072-Team-1\\chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@Parameterized.Parameters
	public static Collection input() {
		return Arrays.asList(new Object[][] {  {"abcdefghijklmno", "1234"
		}, {"errorologin", "234354"}, {"user1", "user1"}, {"mcdlr", "1234$"},
			{"test", "pass"}, {"user", "pass"}});
	}

	@After
	public void tearDown() {
		driver.quit();
	}
	@Test
	public void login() {
		// Test name: Login
		// Step # | name | target | value | comment
		// 1 | open | http://localhost:8080/PMS/ |  | 
		driver.get("http://localhost:8080/PMS/");
		// 2 | setWindowSize | 1200x781 |  | 
		driver.manage().window().setSize(new Dimension(1200, 781));
		// 3 | click | css=li:nth-child(2) span |  | 
		driver.findElement(By.cssSelector("li:nth-child(2) span")).click();
		// 4 | click | id=c |  | 
		driver.findElement(By.id("c")).click();
		// 5 | type | id=c | user | 
		driver.findElement(By.id("c")).sendKeys(username);
		// 7 | click | name=pwd |  | 
		driver.findElement(By.name("pwd")).click();
		// 8 | type | name=pwd | user1 | 
		driver.findElement(By.name("pwd")).sendKeys(pwd);
		// 9 | click | id=submit |  | 
		driver.findElement(By.id("submit")).click();
		//driver.findElement(By.cssSelector("h1")).click();
		String result = driver.findElement(By.cssSelector("h1")).getText();
		assertNotNull(result);
		//    if (result.equals("Error :Admin account not found")) {
		//    	throw new NotFoundException();
		//    }
		assertTrue((result.equals("Payroll Management System : Employer Module")) || (result.equals("Error :Admin account not found")));
		//assertEquals(driver.findElement(By.cssSelector("h1")).getText(), "Payroll Management System : Employer Module");
		// assertEquals(driver.findElement(By.cssSelector("h1")).getText(), "Payroll Management System : Employer Module");
	}
}
