package systemTests;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import model.ModelFacade;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

@RunWith(Parameterized.class)
public class LogoutTest {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	private String username;
	private String pwd;
	
	public LogoutTest(String username, String pwd) {
		super();
		this.username = username;
		this.pwd = pwd;
	}

	@Before
	public void setUp() {
		// Setting up path to Google Chrome driver (chdriver)
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\kianm\\repos\\CEN4072-Team-1\\chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		// Processing other test environment requirements using ModelFacade
		// Employer Login Requirement
		String loginResult = ModelFacade.Employerauthenticate(username, pwd);
	}

	@Parameterized.Parameters
	public static Collection input() {
		return Arrays.asList(new Object[][] {  {"abcdefghijklmno", "1234"
		}, {"errorologin", "234354"}, {"user1", "user1"}, {"mcdlr", "1234$"},
			{"test", "pass"}, {"user", "pass"}});
	}

	@After
	public void tearDown() {
		driver.quit();
	}
	@Test
	public void logout() {
		// Test name: Logout
		// Step # | name | target | value | comment
		// 1 | open | http://localhost:8080/PMS/emplrhome.jsp |  | 
		driver.get("http://localhost:8080/PMS/emplrhome.jsp");
		// 2 | setWindowSize | 1200x781 |  | 
		driver.manage().window().setSize(new Dimension(1200, 781));
		// 3 | click | linkText=Logout |  | 
		driver.findElement(By.linkText("Logout")).click();
		// 4 | click | css=h1 |  | 
		driver.findElement(By.cssSelector("h1")).click();
		String result = driver.findElement(By.cssSelector("h1")).getText();
		assertNotNull(result);
		assertTrue(result.contains("Payroll Management System"));

	}
}
