// Generated by Selenium IDE
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

@RunWith(Parameterized.class)
public class ModifyTSTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  private String empID;
	private String lunchOut;
	private String lunchIn;
	private String totalHours;
	private String editDate;

	public ModifyTSTest(String empID, String lunchOut, String lunchIn, String totalHours, String editDate) {
		super();
		this.empID = empID;
		this.lunchOut = lunchOut;
		this.lunchIn = lunchIn;
		this.totalHours= totalHours;
		this.editDate = editDate;
	}
  


	@Before
	public void setUp() {
		// Setting up path to Google Chrome driver (chdriver)
		System.setProperty("webdriver.chrome.driver", "/Users/kianmaroofi/git/repository/PMS/chdriver");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@Parameterized.Parameters
	public static Collection input() {
		return Arrays.asList(new Object[][] { 
			{"1", "12:00:00", "13:00:00", "11", "2020-02-29"},
			{"1", "12:00:00", "13:00:00", "11", "2020-02-29"},
			{"1", "12:00:00", "13:00:00", "11", "2020-02-29"},
			{"99", "12:00:00", "13:00:00", "11", "2020-02-29"},
			{"99", "12:00:00", "13:00:00", "11", "2020-02-29"},
			{"99", "12:00:00", "13:00:00", "11", "2020-02-29"}
		});
	}
  
  
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void modifyTS() {
    // Test name: ModifyTS
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/PMS/emplrhome.jsp |  | 
    driver.get("http://localhost:8080/PMS/emplrhome.jsp");
    // 2 | setWindowSize | 1200x781 |  | 
    driver.manage().window().setSize(new Dimension(1200, 781));
    // 3 | click | linkText=View Time Sheets |  | 
    driver.findElement(By.linkText("View Time Sheets")).click();
    // 4 | click | name=eid |  | 
    driver.findElement(By.name("eid")).click();
    // 5 | select | name=eid | label=1 | 
    {
      WebElement dropdown = driver.findElement(By.name("eid"));
      dropdown.findElement(By.xpath(String.format("//option[. = '%s']", empID))).click();
    }
    // 6 | click | id=submit |  | 
    driver.findElement(By.id("submit")).click();
    // 7 | click | name=lunchout1 |  | 
    driver.findElement(By.name("lunchout1")).click();
    // 8 | type | name=lunchout1 | 12:00:00 | 
    driver.findElement(By.name("lunchout1")).sendKeys(lunchOut);
    // 9 | click | name=lunchin1 |  | 
    driver.findElement(By.name("lunchin1")).click();
    // 10 | type | name=lunchin1 | 13:00:00 | 
    driver.findElement(By.name("lunchin1")).sendKeys(lunchIn);
    // 11 | click | name=thours1 |  | 
    driver.findElement(By.name("thours1")).click();
    // 12 | type | name=thours1 | 11 | 
    driver.findElement(By.name("thours1")).sendKeys(totalHours);
    // 13 | click | name=date1 |  | 
    driver.findElement(By.name("date1")).click();
    // 14 | type | name=date1 | 2020-02-29 | 
    driver.findElement(By.name("date1")).sendKeys(editDate);
    // 15 | click | css=form > #submit |  | 
    driver.findElement(By.cssSelector("form > #submit")).click();
    // 16 | close |  |  | 
    driver.close();
  }
}
